MODULE idlvideo
DESCRIPTION IDL interface for video capture with OpenCV
VERSION 0.5
SOURCE David Grier
BUILD_DATE MAR 14 2015
FUNCTION IDLVIDEO_CAPTUREFROMCAM 0 1
FUNCTION IDLVIDEO_READ 1 2
FUNCTION IDLVIDEO_GETPROPERTY 2 2
FUNCTION IDLVIDEO_SETPROPERTY 3 3
PROCEDURE IDLVIDEO_RELEASECAPTURE 1 1
